name: Actions Ecosystem Edit Label
description: Edit issue label.
author: The Actions Ecosystem Authors
inputs:
  repo:
    description: GitHub repository
    required: true
    default: ${{ github.event.repository.full_name }}
  github_token:
    description: A GitHub token.
    required: false
    default: ${{ github.token }}
  name:
    description: The label name to be edited.
    required: true
  new_name:
    description: The new name of the label. Emoji can be added to label names, using either native emoji or colon-style markup
    required: false
  color:
    description: The hexadecimal color code for the label, without the leading \#.
    required: false
  description:
    description: The new name of the label. Emoji can be added to label names, using either native emoji or colon-style markup.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: bookmark
  color: green
